baseURL = 'https://freerangetolic.com'
languageCode = 'en-us'
title = "Tolics Engineering Mind"
theme = 'freerange'

[pagination]
pagerSize = 12

[params]
env = "production"
title = "Tolics Engineering Mind"
description = ""
keywords = ["AI", "software architecture", "automation", "startup", "engineering"]
author = "Tolic Kukul"

# Analytics
[services]
[services.googleAnalytics]
ID = "G-S5Y4QVCKH6"

# Search Console verification (optional)
[params.analytics]
[params.analytics.google]
SiteVerificationTag = ""  # Replace with your Google Search Console verification code

# Site-wide default images and Open Graph
images = ["/og-default.png"]  # Default Open Graph image

# Theme settings
defaultTheme = "dark"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
ShowToc = true
TocOpen = false

# Search settings
[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "description", "content"]

# Profile mode for homepage
[params.profileMode]
enabled = false
title = "Tolics Engineering Mind"
subtitle = "// Software Architect & Visionary"
imageUrl = ""
imageWidth = 120
imageHeight = 120

# Show posts on homepage
[params.homeInfoParams]
Title = "Tolics Engineering Mind"
Content = ""
imageTitle = "Tolics"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[[params.profileMode.buttons]]
name = "About"
url = "about"

[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

# Social icons
[[params.socialIcons]]
name = "github"
url = "https://github.com/kukula"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/freerangetolic"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/tolic/"

[[params.socialIcons]]
name = "rss"
url = "index.xml"

# Menu
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "consulting"
name = "Consulting"
url = "/consulting/"
weight = 2

[[menu.main]]
identifier = "series"
name = "Series"
url = "/series/"
weight = 3

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 4

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 5


# Markup settings
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
lineNos = true
noClasses = false
anchorLineNos = true
codeFences = true
guessSyntax = true
lineNumbersInTable = true

# Taxonomies
[taxonomies]
tag = "tags"
category = "categories"
series = "series"

# Output formats
[outputs]
home = ["HTML", "RSS", "JSON"]

# Minification settings
[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = false
minifyOutput = true
[minify.tdewolff]
[minify.tdewolff.css]
keepCSS2 = true
precision = 0
[minify.tdewolff.html]
keepComments = false
keepDefaultAttrVals = true
keepDocumentTags = true
keepEndTags = true
keepQuotes = false
keepWhitespace = false
